name: API Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/api-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  api-tests:
    name: 🧪 Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: 🔧 Build and Test
        run: |
          cd backend
          mvn clean compile test --no-transfer-progress

      - name: 📊 Upload Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            backend/target/surefire-reports/
            backend/target/cucumber-reports/
          retention-days: 7

      - name: ✅ Test Summary
        if: always()
        run: |
          echo "## 🎯 API Test Results" >> $GITHUB_STEP_SUMMARY
          echo "### 📅 Execution: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "### ✅ Status: COMPLETED" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "📊 **Test reports available in Artifacts**" >> $GITHUB_STEP_SUMMARY