name: Frontend E2E Tests

on:
  push:
    branches: [main, develop]
    paths:
      - 'frontend/**'                   # ✅ MUDOU: monitora pasta frontend
      - '.github/workflows/frontend-tests.yml'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'                   # ✅ MUDOU

jobs:
  cypress-e2e:
    name: Cypress E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd frontend                    # ✅ ADICIONAR: entrar na pasta frontend
          npm install

      - name: Run Cypress tests
        run: |
          cd frontend                    # ✅ ADICIONAR: entrar na pasta frontend
          npx cypress run --headless

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-results
          path: |
            frontend/cypress/screenshots/    # ✅ ATUALIZAR: adicionar frontend/
            frontend/cypress/videos/         # ✅ ATUALIZAR
          retention-days: 7