name: Frontend E2E Tests

on:
  push:
    branches: [main, develop]
    paths:
      - 'cypress/**'
      - 'package.json'
      - 'cypress.config.js'
      - '.github/workflows/frontend-tests.yml'

jobs:
  cypress-e2e:
    name: Cypress E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # ✅ NODE 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --headless  # ✅ HEADLESS MODE

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-results
          path: |
            cypress/screenshots/
            cypress/videos/
          retention-days: 7