name: Frontend E2E Tests

on:
  push:
    branches: [main, develop]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-tests.yml'
  pull_request:
    branches: [main]

jobs:
  cypress-e2e:
    name: Cypress E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'  # ✅ ADICIONAR ISSO

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run Cypress tests
        run: |
          cd frontend
          npx cypress run --headless

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-results
          path: |
            frontend/cypress/screenshots/
            frontend/cypress/videos/
          retention-days: 7